DROP TABLE schedule CASCADE CONSTRAINTS;
DROP TABLE movies CASCADE CONSTRAINTS;
DROP TABLE genres CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE roles CASCADE CONSTRAINTS;
CREATE TABLE genres
  (
    ID        INTEGER NOT NULL CONSTRAINT genresIDPrimaryKey PRIMARY KEY,
    GenreName VARCHAR2(35) NOT NULL
  );
CREATE TABLE Movies
  (
    ID       INTEGER NOT NULL CONSTRAINT MoviesIDPrimaryKey PRIMARY KEY,
    Title    VARCHAR2(35) NOT NULL,
    Duration TIMESTAMP ,
    TicletPrice FLOAT ,
    GenreID     INTEGER NOT NULL CONSTRAINT genreIDGenresForeignKey REFERENCES genres(ID),
    YoutubeLink VARCHAR2(200) NOT NULL,
    Description VARCHAR2(1000)NOT NULL
  );
CREATE TABLE schedule
  (
    ID       INTEGER NOT NULL CONSTRAINT scheduleIDprimaryKey PRIMARY KEY,
    MovieID  INTEGER NOT NULL CONSTRAINT movieIdForeignKey REFERENCES movies(ID),
    ShowDate DATE NOT NULL
  );
CREATE TABLE roles
  (
    ID       INTEGER NOT NULL CONSTRAINT rolesIDprimaryKey PRIMARY KEY,
    RoleName VARCHAR2(25) NOT NULL
  );
CREATE TABLE users
  (
    ID        INTEGER NOT NULL CONSTRAINT usersIdPrimaryKey PRIMARY KEY,
    Password  VARCHAR2(16) NOT NULL,
    RoleID    INTEGER NOT NULL CONSTRAINT usersRoleIdForeignKey REFERENCES roles(ID),
    FirstName VARCHAR2(20) NOT NULL ,
    LastName  VARCHAR2(20) NOT NULL,
    Gmail     VARCHAR2(40) NOT NULL
  );

